[Genially] Add Genially resources to the list
abhivaikar/howtheytest pull request #102
Opened 2022-02-03 10:33 UTC by estefafdez

As QA Engineer Manager in Genially, I would love to add our resources and how we test on the list. Also, I've added a Cypress workshop that a member of the QA Team did.

2022-02-11 12:18 UTC, estefafdez commented
Hello! we would love to be on that list :)

2022-02-12 03:31 UTC, abhivaikar requested changes

2022-02-12 03:31 UTC, abhivaikar commented on README.md
> +* [Cypress Workshop by @josefrnandezz](https://www.youtube.com/watch?v=-E3xKywhXXM)
This seems to be a generic Cypress tutorial workshop rather than an experience talking about adoption of Cypress in Genially.

May I request to remove this?

2022-02-12 03:32 UTC, abhivaikar commented
Hello @estefafdez. Thanks a lot for volunteering to add how software is tested at Genially. Really appreciate 💪🏼 

There's a minor review comment. Could you please help address it?

2023-01-03 08:02 UTC, closed without merging