Netfix A/B Testing Article added
abhivaikar/howtheytest pull request #63
Opened 2020-10-10 06:43 UTC by optimist2309

2020-10-10 11:46 UTC, abhivaikar requested changes
Hey @optimist2309. Thanks for the PR. Please refer to one comment I added. Thanks!

2020-10-10 11:46 UTC, abhivaikar commented on README.md
> +  <img src="https://contributors-img.web.app/image?repo=optimist2309/howtheytest" />
This should remain the way it is as the contributors are picked up from the original repository not forks.

2020-10-11 19:14 UTC, optimist2309 commented on README.md
> +  <img src="https://contributors-img.web.app/image?repo=optimist2309/howtheytest" />
Comments Incorporated !!

2020-10-13 12:28 UTC, abhivaikar approved these changes

2020-10-13 12:28 UTC, merged