Added new entries for multiple companies
abhivaikar/howtheytest pull request #76
Opened 2021-01-10 09:14 UTC by upgundecha

Added new posts from -

* ASOS
* Canva
* Disney+ Hotstar
* Expedia
* Goibibo
* Helpshift
* Mercari

2021-01-14 13:18 UTC, abhivaikar requested changes

2021-01-14 13:18 UTC, abhivaikar commented on README.md
> +* [Why we left manual UI testing behind](https://product.canva.com/automated-visual-testing-at-canva/)
this is the duplicate of the one below

2021-01-14 13:18 UTC, abhivaikar commented on README.md
> +[Unit Testing Apache Spark Applications using Hive Tables](https://medium.com/expedia-group-tech/unit-testing-apache-spark-applications-using-hive-tables-ec653c6f25be)
This needs to be a bullet point

2021-01-14 13:18 UTC, abhivaikar commented on README.md
> +* [Mr. Postman for Integration Testing](https://tech.goibibo.com/mr-postman-for-integration-testing-879a4031f916)
Duplicate. The link is already there.

2021-01-14 13:18 UTC, abhivaikar commented on README.md
> +* [The Convoluted Magic of Leiningen Test Selectors](https://medium.com/helpshift-engineering/the-convoluted-magic-of-leiningen-test-selectors-2eb6c452dfcf)
Duplicated.

2021-01-14 13:31 UTC, upgundecha commented on README.md
> +* [The Convoluted Magic of Leiningen Test Selectors](https://medium.com/helpshift-engineering/the-convoluted-magic-of-leiningen-test-selectors-2eb6c452dfcf)
Removed

2021-01-14 13:31 UTC, upgundecha commented on README.md
> +* [Mr. Postman for Integration Testing](https://tech.goibibo.com/mr-postman-for-integration-testing-879a4031f916)
Bad search in my IDE :(

2021-01-14 13:32 UTC, upgundecha commented on README.md
> +[Unit Testing Apache Spark Applications using Hive Tables](https://medium.com/expedia-group-tech/unit-testing-apache-spark-applications-using-hive-tables-ec653c6f25be)
Fixed

2021-01-14 13:32 UTC, upgundecha commented on README.md
> +* [Why we left manual UI testing behind](https://product.canva.com/automated-visual-testing-at-canva/)
Ah title. Fixed

2021-01-26 04:49 UTC, abhivaikar approved these changes

2021-01-26 04:49 UTC, merged